import Test from 'components/Test';
import type { NextPage } from 'next';
import Head from 'next/head';
import { DivTest, H1Test } from 'styles';

const Home: NextPage = () => (
  <div className="root">
    <Head>
      <title>Wine</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
      <DivTest>
        <H1Test>
          <Test />
        </H1Test>
      </DivTest>
    </div>
  </div>
);

export default Home;
